CREATE TABLE USERS (
   id SERIAL PRIMARY KEY,
   login VARCHAR(255) NOT NULL UNIQUE,
   password VARCHAR(255) NOT NULL
);

CREATE TABLE SESSIONS (
   id SERIAL PRIMARY KEY,
   user_id INT NOT NULL,
   uuid VARCHAR(255) NOT NULL UNIQUE,
   FOREIGN KEY (user_id) REFERENCES USERS(id)
);
